### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aehlke** [darinf/ios-playground#2]
Please add a license such as MIT, BSD, Apache - you have some nice work here, particularly the working demo of obscuredInsets. Thank you

**Comment by aehlke** [comment]
hi @darinf just pinging you on this as I notice the repo is still active :) thank you

**Comment by darinf** [comment]
> hi @darinf just pinging you on this as I notice the repo is still active :) thank you

Hey there, sorry I didn't notice the issue you filed long ago. Appreciate the ping! I'll add a license.

**Comment by darinf** [comment]
Resolved: https://github.com/darinf/ios-playground/commit/91bade2f92c987496284a69c994e9a112e291c98

**Comment by aehlke** [comment]
Thank you! Much appreciated. Great work, and inspiring for my language-learning browser if you're curious: https://reader.manabi.io
